### ISSUE TITLE
Add a readme file for better understanding

### ISSUE THREAD

**Issue by shouvikbhuiyan1990** [iamparthaonline/Chrome-Extension-for-getting-component-JSONs-for-AEM-React-Project#1]
Step by step Installation guide would be really helpful

**Comment by iamparthaonline** [comment]
I will add it tonight.

**Comment by iamparthaonline** [comment]
Added the much needed instructions. 

[ Added readme.md ](https://github.com/iamparthaonline/Chrome-Extension-for-getting-component-JSONs-for-AEM-React-Project/commit/a4e2095cdb6e2106ff56c0abc5538d838d550c66)
